server:
  port: 8090
  servlet:
    context-path: /apiserver

spring:
  #数据源配置
  datasource:
    druid:
      url: jdbc:mysql://42.194.228.203:3306/mdis?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 3.14159
      driver-class-name: com.mysql.cj.jdbc.Driver

  
  # Spring Boot 2.6.X与Swagger 2.9.2兼容性配置
  mvc:
    static-path-pattern: /**
    pathmatch:
      matching-strategy: ant_path_matcher


  # JSON日期格式配置
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8


# MyBatis-Plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印SQL日志
    map-underscore-to-camel-case: true # 下划线转驼峰命名法
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.thefive.apiserver.pojo,com..vo,com.thefive.apiserver.dto

