# MySQL?????
jdbc.driver=com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql://42.194.228.203:3306/mdis?useSSL=false&serverTimezone=UTC
jdbc.username=root
jdbc.password=3.14159

# MyBatis-Plus??
mybatis-plus.mapper-locations=classpath:mapper/*.xml
mybatis-plus.type-aliases-package=com.thefive.apiserver.pojo
